[31m[1m19:41:32.36 <error> BadRequestError: none
    at Object.throw (C:\Users\sinner\Desktop\my-blog\server\node_modules\_koa@2.2.0@koa\lib\context.js:91:23)
    at createArticle (C:\Users\sinner\Desktop\my-blog\server\controllers\article.js:15:22)
    at dispatch (C:\Users\sinner\Desktop\my-blog\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\sinner\Desktop\my-blog\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at C:\Users\sinner\Desktop\my-blog\server\node_modules\_koa-router@7.2.0@koa-router\lib\router.js:345:16
    at dispatch (C:\Users\sinner\Desktop\my-blog\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at C:\Users\sinner\Desktop\my-blog\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:36:12
    at dispatch (C:\Users\sinner\Desktop\my-blog\server\node_modules\_koa-router@7.2.0@koa-router\lib\router.js:350:31)
    at dispatch (C:\Users\sinner\Desktop\my-blog\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\sinner\Desktop\my-blog\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at module.exports (C:\Users\sinner\Desktop\my-blog\server\middlewares\errorHandle.js:20:15)
    at dispatch (C:\Users\sinner\Desktop\my-blog\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\sinner\Desktop\my-blog\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at module.exports (C:\Users\sinner\Desktop\my-blog\server\middlewares\response.js:13:11)
    at dispatch (C:\Users\sinner\Desktop\my-blog\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\sinner\Desktop\my-blog\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18) (in errorHandle.js:29)[22m[39m
[31m[1m19:42:57.56 <error> BadRequestError: none
    at Object.throw (C:\Users\sinner\Desktop\my-blog\server\node_modules\_koa@2.2.0@koa\lib\context.js:91:23)
    at createArticle (C:\Users\sinner\Desktop\my-blog\server\controllers\article.js:15:22)
    at dispatch (C:\Users\sinner\Desktop\my-blog\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\sinner\Desktop\my-blog\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at C:\Users\sinner\Desktop\my-blog\server\node_modules\_koa-router@7.2.0@koa-router\lib\router.js:345:16
    at dispatch (C:\Users\sinner\Desktop\my-blog\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at C:\Users\sinner\Desktop\my-blog\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:36:12
    at dispatch (C:\Users\sinner\Desktop\my-blog\server\node_modules\_koa-router@7.2.0@koa-router\lib\router.js:350:31)
    at dispatch (C:\Users\sinner\Desktop\my-blog\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\sinner\Desktop\my-blog\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at module.exports (C:\Users\sinner\Desktop\my-blog\server\middlewares\errorHandle.js:20:15)
    at dispatch (C:\Users\sinner\Desktop\my-blog\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\sinner\Desktop\my-blog\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at module.exports (C:\Users\sinner\Desktop\my-blog\server\middlewares\response.js:13:11)
    at dispatch (C:\Users\sinner\Desktop\my-blog\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\sinner\Desktop\my-blog\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18) (in errorHandle.js:29)[22m[39m
[31m[1m19:55:42.15 <error> MongooseError: article validation failed: 
    at ValidationError (C:\Users\sinner\Desktop\my-blog\server\node_modules\_mongoose@4.10.4@mongoose\lib\error\validation.js:26:11)
    at model.Document.invalidate (C:\Users\sinner\Desktop\my-blog\server\node_modules\_mongoose@4.10.4@mongoose\lib\document.js:1594:32)
    at model.Document.set (C:\Users\sinner\Desktop\my-blog\server\node_modules\_mongoose@4.10.4@mongoose\lib\document.js:753:10)
    at model._handleIndex (C:\Users\sinner\Desktop\my-blog\server\node_modules\_mongoose@4.10.4@mongoose\lib\document.js:587:14)
    at model.Document.set (C:\Users\sinner\Desktop\my-blog\server\node_modules\_mongoose@4.10.4@mongoose\lib\document.js:547:24)
    at model.Document (C:\Users\sinner\Desktop\my-blog\server\node_modules\_mongoose@4.10.4@mongoose\lib\document.js:71:12)
    at model.Model (C:\Users\sinner\Desktop\my-blog\server\node_modules\_mongoose@4.10.4@mongoose\lib\model.js:46:12)
    at new model (C:\Users\sinner\Desktop\my-blog\server\node_modules\_mongoose@4.10.4@mongoose\lib\model.js:3614:13)
    at createArticle (C:\Users\sinner\Desktop\my-blog\server\controllers\article.js:22:23)
    at dispatch (C:\Users\sinner\Desktop\my-blog\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\sinner\Desktop\my-blog\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at C:\Users\sinner\Desktop\my-blog\server\node_modules\_koa-router@7.2.0@koa-router\lib\router.js:345:16
    at dispatch (C:\Users\sinner\Desktop\my-blog\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at C:\Users\sinner\Desktop\my-blog\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:36:12
    at dispatch (C:\Users\sinner\Desktop\my-blog\server\node_modules\_koa-router@7.2.0@koa-router\lib\router.js:350:31)
    at dispatch (C:\Users\sinner\Desktop\my-blog\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32) (in errorHandle.js:29)[22m[39m
[31m[1m19:56:34.72 <error> MongooseError: article validation failed: 
    at ValidationError (C:\Users\sinner\Desktop\my-blog\server\node_modules\_mongoose@4.10.4@mongoose\lib\error\validation.js:26:11)
    at model.Document.invalidate (C:\Users\sinner\Desktop\my-blog\server\node_modules\_mongoose@4.10.4@mongoose\lib\document.js:1594:32)
    at model.Document.set (C:\Users\sinner\Desktop\my-blog\server\node_modules\_mongoose@4.10.4@mongoose\lib\document.js:753:10)
    at model._handleIndex (C:\Users\sinner\Desktop\my-blog\server\node_modules\_mongoose@4.10.4@mongoose\lib\document.js:587:14)
    at model.Document.set (C:\Users\sinner\Desktop\my-blog\server\node_modules\_mongoose@4.10.4@mongoose\lib\document.js:547:24)
    at model.Document (C:\Users\sinner\Desktop\my-blog\server\node_modules\_mongoose@4.10.4@mongoose\lib\document.js:71:12)
    at model.Model (C:\Users\sinner\Desktop\my-blog\server\node_modules\_mongoose@4.10.4@mongoose\lib\model.js:46:12)
    at new model (C:\Users\sinner\Desktop\my-blog\server\node_modules\_mongoose@4.10.4@mongoose\lib\model.js:3614:13)
    at createArticle (C:\Users\sinner\Desktop\my-blog\server\controllers\article.js:22:23)
    at dispatch (C:\Users\sinner\Desktop\my-blog\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\sinner\Desktop\my-blog\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at C:\Users\sinner\Desktop\my-blog\server\node_modules\_koa-router@7.2.0@koa-router\lib\router.js:345:16
    at dispatch (C:\Users\sinner\Desktop\my-blog\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at C:\Users\sinner\Desktop\my-blog\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:36:12
    at dispatch (C:\Users\sinner\Desktop\my-blog\server\node_modules\_koa-router@7.2.0@koa-router\lib\router.js:350:31)
    at dispatch (C:\Users\sinner\Desktop\my-blog\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32) (in errorHandle.js:29)[22m[39m
[31m[1m19:58:40.81 <error> MongooseError: article validation failed: 
    at ValidationError (C:\Users\sinner\Desktop\my-blog\server\node_modules\_mongoose@4.10.4@mongoose\lib\error\validation.js:26:11)
    at model.Document.invalidate (C:\Users\sinner\Desktop\my-blog\server\node_modules\_mongoose@4.10.4@mongoose\lib\document.js:1594:32)
    at model.Document.set (C:\Users\sinner\Desktop\my-blog\server\node_modules\_mongoose@4.10.4@mongoose\lib\document.js:753:10)
    at model._handleIndex (C:\Users\sinner\Desktop\my-blog\server\node_modules\_mongoose@4.10.4@mongoose\lib\document.js:587:14)
    at model.Document.set (C:\Users\sinner\Desktop\my-blog\server\node_modules\_mongoose@4.10.4@mongoose\lib\document.js:547:24)
    at model.Document (C:\Users\sinner\Desktop\my-blog\server\node_modules\_mongoose@4.10.4@mongoose\lib\document.js:71:12)
    at model.Model (C:\Users\sinner\Desktop\my-blog\server\node_modules\_mongoose@4.10.4@mongoose\lib\model.js:46:12)
    at new model (C:\Users\sinner\Desktop\my-blog\server\node_modules\_mongoose@4.10.4@mongoose\lib\model.js:3614:13)
    at createArticle (C:\Users\sinner\Desktop\my-blog\server\controllers\article.js:22:23)
    at dispatch (C:\Users\sinner\Desktop\my-blog\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\sinner\Desktop\my-blog\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at C:\Users\sinner\Desktop\my-blog\server\node_modules\_koa-router@7.2.0@koa-router\lib\router.js:345:16
    at dispatch (C:\Users\sinner\Desktop\my-blog\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at C:\Users\sinner\Desktop\my-blog\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:36:12
    at dispatch (C:\Users\sinner\Desktop\my-blog\server\node_modules\_koa-router@7.2.0@koa-router\lib\router.js:350:31)
    at dispatch (C:\Users\sinner\Desktop\my-blog\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32) (in errorHandle.js:29)[22m[39m
[31m[1m19:59:57.03 <error> MongooseError: article validation failed: 
    at ValidationError (C:\Users\sinner\Desktop\my-blog\server\node_modules\_mongoose@4.10.4@mongoose\lib\error\validation.js:26:11)
    at model.Document.invalidate (C:\Users\sinner\Desktop\my-blog\server\node_modules\_mongoose@4.10.4@mongoose\lib\document.js:1594:32)
    at model.Document.set (C:\Users\sinner\Desktop\my-blog\server\node_modules\_mongoose@4.10.4@mongoose\lib\document.js:753:10)
    at model._handleIndex (C:\Users\sinner\Desktop\my-blog\server\node_modules\_mongoose@4.10.4@mongoose\lib\document.js:587:14)
    at model.Document.set (C:\Users\sinner\Desktop\my-blog\server\node_modules\_mongoose@4.10.4@mongoose\lib\document.js:547:24)
    at model.Document (C:\Users\sinner\Desktop\my-blog\server\node_modules\_mongoose@4.10.4@mongoose\lib\document.js:71:12)
    at model.Model (C:\Users\sinner\Desktop\my-blog\server\node_modules\_mongoose@4.10.4@mongoose\lib\model.js:46:12)
    at new model (C:\Users\sinner\Desktop\my-blog\server\node_modules\_mongoose@4.10.4@mongoose\lib\model.js:3614:13)
    at createArticle (C:\Users\sinner\Desktop\my-blog\server\controllers\article.js:22:23)
    at dispatch (C:\Users\sinner\Desktop\my-blog\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\sinner\Desktop\my-blog\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at C:\Users\sinner\Desktop\my-blog\server\node_modules\_koa-router@7.2.0@koa-router\lib\router.js:345:16
    at dispatch (C:\Users\sinner\Desktop\my-blog\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at C:\Users\sinner\Desktop\my-blog\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:36:12
    at dispatch (C:\Users\sinner\Desktop\my-blog\server\node_modules\_koa-router@7.2.0@koa-router\lib\router.js:350:31)
    at dispatch (C:\Users\sinner\Desktop\my-blog\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32) (in errorHandle.js:29)[22m[39m
[31m[1m20:00:07.82 <error> MongooseError: article validation failed: 
    at ValidationError (C:\Users\sinner\Desktop\my-blog\server\node_modules\_mongoose@4.10.4@mongoose\lib\error\validation.js:26:11)
    at model.Document.invalidate (C:\Users\sinner\Desktop\my-blog\server\node_modules\_mongoose@4.10.4@mongoose\lib\document.js:1594:32)
    at model.Document.set (C:\Users\sinner\Desktop\my-blog\server\node_modules\_mongoose@4.10.4@mongoose\lib\document.js:753:10)
    at model._handleIndex (C:\Users\sinner\Desktop\my-blog\server\node_modules\_mongoose@4.10.4@mongoose\lib\document.js:587:14)
    at model.Document.set (C:\Users\sinner\Desktop\my-blog\server\node_modules\_mongoose@4.10.4@mongoose\lib\document.js:547:24)
    at model.Document (C:\Users\sinner\Desktop\my-blog\server\node_modules\_mongoose@4.10.4@mongoose\lib\document.js:71:12)
    at model.Model (C:\Users\sinner\Desktop\my-blog\server\node_modules\_mongoose@4.10.4@mongoose\lib\model.js:46:12)
    at new model (C:\Users\sinner\Desktop\my-blog\server\node_modules\_mongoose@4.10.4@mongoose\lib\model.js:3614:13)
    at createArticle (C:\Users\sinner\Desktop\my-blog\server\controllers\article.js:22:23)
    at dispatch (C:\Users\sinner\Desktop\my-blog\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\sinner\Desktop\my-blog\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at C:\Users\sinner\Desktop\my-blog\server\node_modules\_koa-router@7.2.0@koa-router\lib\router.js:345:16
    at dispatch (C:\Users\sinner\Desktop\my-blog\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at C:\Users\sinner\Desktop\my-blog\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:36:12
    at dispatch (C:\Users\sinner\Desktop\my-blog\server\node_modules\_koa-router@7.2.0@koa-router\lib\router.js:350:31)
    at dispatch (C:\Users\sinner\Desktop\my-blog\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32) (in errorHandle.js:29)[22m[39m
[31m[1m21:08:51.39 <error> TypeError: Cannot read property 'populate' of undefined
    at createArticle (C:\Users\sinner\Desktop\my-blog\server\controllers\article.js:39:21)
    at process._tickCallback (internal/process/next_tick.js:103:7) (in errorHandle.js:29)[22m[39m
[31m[1m21:13:09.30 <error> TypeError: Cannot read property 'populate' of undefined
    at createArticle (C:\Users\sinner\Desktop\my-blog\server\controllers\article.js:39:21)
    at process._tickCallback (internal/process/next_tick.js:103:7) (in errorHandle.js:29)[22m[39m
[31m[1m21:36:53.27 <error> MongooseError: Cast to ObjectId failed for value "asdasdds" at path "_id"
    at CastError (C:\Users\sinner\Desktop\my-blog\server\node_modules\_mongoose@4.10.4@mongoose\lib\error\cast.js:26:11)
    at ObjectId.cast (C:\Users\sinner\Desktop\my-blog\server\node_modules\_mongoose@4.10.4@mongoose\lib\schema\objectid.js:149:13)
    at ObjectId.SchemaType._castForQuery (C:\Users\sinner\Desktop\my-blog\server\node_modules\_mongoose@4.10.4@mongoose\lib\schematype.js:1023:15)
    at ObjectId.castForQuery (C:\Users\sinner\Desktop\my-blog\server\node_modules\_mongoose@4.10.4@mongoose\lib\schema\objectid.js:189:15)
    at cast (C:\Users\sinner\Desktop\my-blog\server\node_modules\_mongoose@4.10.4@mongoose\lib\cast.js:232:32)
    at model.Query.Query.cast (C:\Users\sinner\Desktop\my-blog\server\node_modules\_mongoose@4.10.4@mongoose\lib\query.js:2933:12)
    at model.Query.Query.findOne (C:\Users\sinner\Desktop\my-blog\server\node_modules\_mongoose@4.10.4@mongoose\lib\query.js:1394:10)
    at C:\Users\sinner\Desktop\my-blog\server\node_modules\_mongoose@4.10.4@mongoose\lib\query.js:2746:21
    at model.Query.exec (C:\Users\sinner\Desktop\my-blog\server\node_modules\_mongoose@4.10.4@mongoose\lib\query.js:2740:17)
    at model.Query.Query.then (C:\Users\sinner\Desktop\my-blog\server\node_modules\_mongoose@4.10.4@mongoose\lib\query.js:2788:15)
    at getArticleById (C:\Users\sinner\Desktop\my-blog\server\controllers\article.js:55:49)
    at dispatch (C:\Users\sinner\Desktop\my-blog\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\sinner\Desktop\my-blog\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at C:\Users\sinner\Desktop\my-blog\server\node_modules\_koa-router@7.2.0@koa-router\lib\router.js:345:16
    at dispatch (C:\Users\sinner\Desktop\my-blog\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at C:\Users\sinner\Desktop\my-blog\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:36:12 (in errorHandle.js:29)[22m[39m
[31m[1m21:47:58.00 <error> TypeError: Cannot read property 'populate' of undefined
    at getArticleById (C:\Users\sinner\Desktop\my-blog\server\controllers\article.js:62:21)
    at process._tickCallback (internal/process/next_tick.js:103:7) (in errorHandle.js:29)[22m[39m
[31m[1m21:59:40.31 <error> BadRequestError: Bad Request
    at Object.throw (C:\Users\sinner\Desktop\my-blog\server\node_modules\_koa@2.2.0@koa\lib\context.js:91:23)
    at Article.findById.catch (C:\Users\sinner\Desktop\my-blog\server\controllers\article.js:65:26)
    at process._tickCallback (internal/process/next_tick.js:103:7) (in errorHandle.js:29)[22m[39m
[31m[1m22:00:26.16 <error> BadRequestError: Bad Request
    at Object.throw (C:\Users\sinner\Desktop\my-blog\server\node_modules\_koa@2.2.0@koa\lib\context.js:91:23)
    at Article.findById.catch (C:\Users\sinner\Desktop\my-blog\server\controllers\article.js:65:26)
    at process._tickCallback (internal/process/next_tick.js:103:7) (in errorHandle.js:29)[22m[39m
[31m[1m22:13:30.95 <error> TypeError: Cannot read property 'body' of undefined
    at getArticleById (C:\Users\sinner\Desktop\my-blog\server\controllers\article.js:73:25)
    at process._tickCallback (internal/process/next_tick.js:103:7) (in errorHandle.js:29)[22m[39m
[31m[1m22:14:06.70 <error> TypeError: Cannot read property 'body' of undefined
    at getArticleById (C:\Users\sinner\Desktop\my-blog\server\controllers\article.js:73:25)
    at process._tickCallback (internal/process/next_tick.js:103:7) (in errorHandle.js:29)[22m[39m
[31m[1m22:16:19.47 <error> TypeError: Cannot read property 'body' of undefined
    at getArticleById (C:\Users\sinner\Desktop\my-blog\server\controllers\article.js:73:25)
    at process._tickCallback (internal/process/next_tick.js:103:7) (in errorHandle.js:29)[22m[39m
[31m[1m22:26:41.68 <error> InternalServerError: Internal Server Error
    at Object.throw (C:\Users\sinner\Desktop\my-blog\server\node_modules\_koa@2.2.0@koa\lib\context.js:91:23)
    at Article.findById.catch (C:\Users\sinner\Desktop\my-blog\server\controllers\article.js:56:22)
    at process._tickCallback (internal/process/next_tick.js:103:7) (in errorHandle.js:29)[22m[39m
[31m[1m22:26:58.01 <error> NotFoundError: Not Found
    at Object.throw (C:\Users\sinner\Desktop\my-blog\server\node_modules\_koa@2.2.0@koa\lib\context.js:91:23)
    at Article.findById.catch (C:\Users\sinner\Desktop\my-blog\server\controllers\article.js:56:22)
    at process._tickCallback (internal/process/next_tick.js:103:7) (in errorHandle.js:29)[22m[39m
